name: Deploy Frontend

on:
  push:
    branches: [ frontend ]
    paths:
      - vulnsight-frontend/**
      - .github/workflows/frontend-deploy.yml

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    # Disable React’s “treat warnings as errors” behaviour in CI
    env:
      CI: ""                       # ← makes eslint warnings non-fatal

    steps:
      # 1.  Check out this commit
      - uses: actions/checkout@v4

      # 2.  Set up Node 18 (LTS)
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3.  Install deps and build the React app
      - name: Install & build
        working-directory: vulnsight-frontend
        run: |
          npm ci
          npm run build

      # 4.  Sync the build/ folder to the public S3 bucket
      - name: Sync to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --delete
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION:            ${{ secrets.AWS_REGION }}
          AWS_S3_BUCKET:         ${{ secrets.S3_BUCKET }}
          SOURCE_DIR:            "vulnsight-frontend/build"
